Use relative imports where possible
The exception is Flask because of how the debug-mode
reloads. Causes the following error using relative
import in __main__.py:
ValueError: Attempted relative import in non-package